export const GET_ORDERS_REQUEST = 'GET_ORDERS_REQUEST';
export const GET_ORDERS_COMMIT = 'GET_ORDERS_COMMIT';

export const GET_ITEM_REQUEST = 'GET_ITEM_REQUEST';
export const GET_ITEM_COMMIT = 'GET_ITEM_COMMIT';

export const PUT_ORDER_REQUEST = 'PUT_ORDER_REQUEST';
export const PUT_ORDER_COMMIT = 'PUT_ORDER_COMMIT';