export const GET_ORDERS_REQUEST = 'GET_ORDERS_REQUEST';
export const GET_ORDERS_COMMIT = 'GET_ORDERS_COMMIT';

export const GET_ITEM_REQUEST = 'GET_ITEM_REQUEST';
export const GET_ITEM_COMMIT = 'GET_ITEM_COMMIT';